#!/usr/bin/env python3
"""
Debug script for RowHammer-Inspired Search
This script provides a simplified environment to test functions
and validate the search approach.
"""

import logging
import sys
from rowhammer_search import (
    private_key_to_address,
    address_similarity,
    is_valid_candidate,
    test_candidate,
    TARGET_ADDRESS,
    PREV_TERM_67,
    PREV_TERM_67_INT,
    ESTIMATE_VALUE
)

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(levelname)s: %(message)s',
    handlers=[
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger(__name__)

def main():
    """
    Main debug function
    """
    logger.info("Setting up logging...")
    logger.info("Logging setup complete.\n")
    
    print("==== Starting RowHammer Debug Search ====\n")
    
    # Test base candidates
    print("Testing base candidates...\n")
    
    # Test candidates derived from both recursive formulas and estimates
    test_candidates = [
        PREV_TERM_67_INT,  # Original previous term
        0x79cdae96e7ebdab0776,  # Generated by another formula
        0x734fc235c1940c1af,  # Closer estimate from previous tests
    ]
    
    # Test each candidate and its bit flips
    for base_candidate in test_candidates:
        print(f"Testing candidate: {hex(base_candidate)}")
        test_and_print_result(base_candidate)
        
        # Test bit flips at key positions
        for bit_pos in [0, 4, 8, 16, 32, 64]:
            flipped = base_candidate ^ (1 << bit_pos)
            print(f"Testing bit flip at position {bit_pos}: {hex(flipped)}")
            test_and_print_result(flipped)
        
        print()  # Add spacing between candidates
    
    print("Debug search completed.")

def test_and_print_result(candidate):
    """
    Test a candidate and print the result
    """
    print(f"Testing candidate: {hex(candidate)}")
    
    if not is_valid_candidate(candidate):
        print("Invalid candidate (out of range)")
        match, address, similarity = False, None, 0
    else:
        print(f"Converting private key {hex(candidate)} to address...")
        address = private_key_to_address(candidate)
        print(f"Converted to address: {address}")
        
        similarity = address_similarity(address, TARGET_ADDRESS)
        print(f"Similarity: {similarity:.6f}")
        
        match = (address == TARGET_ADDRESS)
    
    print(f"Result: Match={match}, Address={address}, Similarity={similarity:.6f}")
    return match, address, similarity

if __name__ == "__main__":
    main() 